version: "3"

services:
  siberiana-strapi:
    container_name: siberiana-strapi
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: siberiana-strapi:latest
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: siberiana-strapi-pg
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "1337:1337"
    networks:
      - siberiana-network
    depends_on:
      - siberiana-strapi-pg

  siberiana-strapi-pg:
    container_name: siberiana-strapi-pg
    restart: unless-stopped
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - siberiana-strapi-data:/var/lib/postgresql/data/
    ports:
      - "25432:5432"
    networks:
      - siberiana-network

  siberiana-strapi-adminer:
    container_name: siberiana-strapi-adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "18080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=siberiana-strapi-pg
    networks:
      - siberiana-network
    depends_on:
      - siberiana-strapi-pg

networks:
  siberiana-network:
    name: siberiana-network
    external: true

volumes:
  siberiana-strapi-data:
    external: true
